### ISSUE TITLE
0 CPM

### ISSUE THREAD

**Issue by Microngamer** [h0nde/roblox-claimable-group-finder#14]
Hello, whenever I run it, it says All workers are running, but I get 0 cpm, my proxies and pc both are very good, what can the problem be ?

**Comment by h0nde** [comment]
Try running it without proxies.

**Comment by Microngamer** [comment]
Tried, still not working :|

**Comment by Microngamer** [comment]
@h0nde Uhm?

**Comment by Microngamer** [comment]
Works now after a week
