### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by Randoni** [h0nde/roblox-claimable-group-finder#19]
Hello, I wanted to know how I can make it so the group is sent to discord through a webhook. I'm currently doing "python finder.py --workers 16 --cut-off 11.5m --range 5m-12m --webhook-url" but it doesn't seem to be sending anything. It's either I'm doing it wrong or it's taking more then 3 hours to find a group.

**Comment by h0nde** [comment]
I'm assuming you put your webhook url after the ` --webhook-url` argument. What CPM are you getting?

**Comment by Randoni** [comment]
Yes I did put my url after it. I'm was averaging about 1 mil CPM while I was doing it earlier.
