### ISSUE TITLE
Stuck at 10000 cpm

### ISSUE THREAD

**Issue by zaxhodV2** [h0nde/roblox-claimable-group-finder#20]
so basically its both for windows and replit and its basically slow and stuck at 10k cpm idk if its the threads but you should fix it h0nda and see if theres any problem.

**Comment by zaxhodV2** [comment]
threads are good , workers are good and running just the cpm and its stuck for everyone so idk wth happened + its really slow

**Comment by h0nde** [comment]
The endpoint for batch group details now ratelimits if you send too many requests, therefore the usage of proxies is necessary now.
