### ISSUE TITLE
Barren Server

### ISSUE THREAD

**Issue by Waffledd** [h0nde/roblox-claimable-group-finder#21]
Recently left it open scanning for groups for a few hours. When I came back and looked at the server, I found no groups. My CPM is about 500K. I'm assuming I'm doing something wrong. Currently working with ` python finder.py --workers 16 --cut-off 11.5m --range 4.5m-12m --proxy-file proxies.txt --webhook-url https://discord.com/api/webhooks/(numbers) ` . Let me know if I'm doing something wrong, appreciate it.

**Comment by h0nde** [comment]
500k CPM will take ~23 mins to do a full cycle of scanning, which is just not enough catch up with other competitors (*such as [me](https://i.imgur.com/NYjpXW2.png)*). I recommend trying with better proxies.

**Comment by Waffledd** [comment]
Wow, alright thank you.
