### ISSUE TITLE
How do i properly setup the README? i've tried but don't think i'm getting it right and finder closing after launch

### ISSUE THREAD

**Issue by grandpajohnny** [h0nde/roblox-claimable-group-finder#34]
I have no clue what i'm doing. This is how i've filled in the readme and i'm not sure if it's correct because everytime i run the finder it opens for a bit then closes. The only things i've changed in the README are this: 

-w 10        
-t 5000
-r 9999999
-p proxies.txt
-u https://discord.com/api/webhooks/mywebhook (had to remove it so people don't spam)       
-c 99999999
-C 10
-T 60

Have i set this up properly and if not how do i do it? If  you could provide a pic of your settings/how you set it up it would be much easier, thank

i attached my README below incase i've confused you: (Don't worry i've deleted the webhook in the readme)

[README.md](https://github.com/h0nde/roblox-claimable-group-finder/files/7215827/README.md)
s!

**Comment by grandpajohnny** [comment]
update: i think i'm supposed to put the stuff after python finder.py like this: python finder.py --workers 16 --proxy-file proxies.txt --threads 200 --webhook-url https://discord.com/api/webhooks/

i've done that, made a txt file called proxies and put in https/http proxies but when running finder.py it still closes after a couple seconds. the terminal is also black the entire time

**Comment by grandpajohnny** [comment]
figured it out but what does cpm mean

**Comment by h0nde** [comment]
CPM stands for checks-per-minute, or the amount of group scanned within the last minute.
