### ISSUE TITLE
What proxies recommended for group finder?

### ISSUE THREAD

**Issue by UkrMaksim2009** [h0nde/roblox-claimable-group-finder#41]
What proxies recommended? I need some free proxies, because from all free proxies sites, i get only 5,000,000 CPM, Help please!

**Comment by 4channel** [comment]
"only" 5million cpm

**Comment by UkrMaksim2009** [comment]
> "only" 5million cpm

what's funny? im not from united states, to have good grammar.

**Comment by 4channel** [comment]
![image](https://user-images.githubusercontent.com/68159867/135710294-cbf1745c-fe81-4367-9812-6d1c30aa6d68.png)

5million cpm is pretty good, you aren't getting groups because everyone is using this and people claimed all the groups before you could
