### ISSUE TITLE
How do I do the range part?

### ISSUE THREAD

**Issue by MoeenTheSkid** [h0nde/roblox-claimable-group-finder#51]
Hey! So I would like to make it range from 1 - 15000000 but I do not know how I am supposed to do that.
It says
-r <range> [<range> ...], --range <range> [<range> ...]
I assume we do
-r <range> [<range> ...], --range 1 [15000000  ...]
please tell me if i am right, if not, what do we do?

**Comment by h0nde** [comment]
The tool automatically calibrates it's range from 1 to the most recently created group, so there isn't much point in doing this.

`python finder.py -r 1-15m`
