### ISSUE TITLE
HTTP proxies

### ISSUE THREAD

**Issue by potatoman42o** [h0nde/roblox-claimable-group-finder#52]
how do i get my HTTP proxies

**Comment by MoeenTheSkid** [comment]
You need to buy them or use free ones (less effective)

**Comment by zaxhodV2** [comment]
use sslproxies.org or proxyscrape they are pretty ok

**Comment by MoeenTheSkid** [comment]
I use webshare

**Comment by zaxhodV2** [comment]
i use awmproxy paid ones

**Comment by zaxhodV2** [comment]
much effective
