### ISSUE TITLE
hi im new to this pls help me out

### ISSUE THREAD

**Issue by DeathOmen8055** [h0nde/roblox-claimable-group-finder#59]
is this correct , aslo if i close powercell will it still work?
am i doing something wrong? 
https://cdn.discordapp.com/attachments/909037286052753430/909126221856649257/unknown.png
thanks :)

**Comment by DeathOmen8055** [comment]
follow up question , it didnt send the log to my discord?
![image](https://user-images.githubusercontent.com/94238506/141652655-33a894f4-6d79-464a-a890-16614f9479f9.png)

**Comment by DeathOmen8055** [comment]
wow when i close it reset great!

**Comment by Thazw** [comment]
drop your discord

**Comment by DeathOmen8055** [comment]
> drop your discord

Death Omen ψ#0001

**Comment by DeathOmen8055** [comment]
Death Omen ψ#1111
