### ISSUE TITLE
proxy err

### ISSUE THREAD

**Issue by thatsfishy** [h0nde/roblox-claimable-group-finder#68]
Error while parsing line 1 in proxy file: Exception('Unrecognized proxy format: "2.188.166.25",')
Error while parsing line 2 in proxy file: Exception('Unrecognized proxy format: "89.32.248.206",')
Error while parsing line 3 in proxy file: Exception('Unrecognized proxy format: "47.242.235.25",')
Error while parsing line 4 in proxy file: Exception('Unrecognized proxy format: "45.8.105.66",')
Error while parsing line 5 in proxy file: Exception('Unrecognized proxy format: "203.30.189.95",')
Error while parsing line 6 in proxy file: Exception('Unrecognized proxy format: "203.28.8.250"')
Traceback (most recent call last):
  File "C:\Users\ihate\desktop\roblox-claimable-group-finder-main\finder.py", line 7, in <module>
    controller = Controller(
  File "C:\Users\ihate\desktop\roblox-claimable-group-finder-main\core\controllers.py", line 16, in __init__
    self.load_proxies()
  File "C:\Users\ihate\desktop\roblox-claimable-group-finder-main\core\controllers.py", line 35, in load_proxies
    assert proxies, "Proxy file is empty."
AssertionError: Proxy file is empty.

proxie.txt file:

"2.188.166.25",
"89.32.248.206",
"47.242.235.25",
"45.8.105.66",
"203.30.189.95",
"203.28.8.250"

**Comment by h0nde** [comment]
This is not a standard proxy format, hence why it's not recognized by the tool. Try removing the `"` and `,` characters from your list and it should work.

**Comment by thatsfishy** [comment]
why is it taking 100% of my CPU at 0.01 rpm??
